Vagrant.configure("2") do |config|
 config.vm.box = "precise32"
 config.vm.network :forwarded_port, host: 4567, guest: 80
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
  end
#config.vm.provider "virtualbox" do |v|
#  v.gui = true
#end
end
